### ISSUE TITLE
Slow operations are prohibited on EDT

### ISSUE THREAD

**Issue by AlexPl292** [jonathanlermitage/intellij-extra-icons-plugin#111] opened 2022-09-08 05:05 UTC
```
java.lang.Throwable: Slow operations are prohibited on EDT. See SlowOperations.assertSlowOperationsAreAllowed javadoc.
	at com.intellij.openapi.diagnostic.Logger.error(Logger.java:184)
	at com.intellij.util.SlowOperations.assertSlowOperationsAreAllowed(SlowOperations.java:103)
	at com.intellij.util.indexing.FileBasedIndexScanUtil.ensureUpToDate(FileBasedIndexScanUtil.java:47)
	at com.intellij.util.indexing.FileBasedIndexScanUtil.processFilesContainingAnyKey(FileBasedIndexScanUtil.java:233)
	at com.intellij.util.indexing.FileBasedIndexImpl.processFilesContainingAnyKey(FileBasedIndexImpl.java:1162)
	at com.intellij.psi.search.FilenameIndex.getVirtualFilesByNames(FilenameIndex.java:219)
	at com.intellij.psi.search.FilenameIndex.getVirtualFilesByName(FilenameIndex.java:56)
	at com.intellij.psi.search.FilenameIndex.getVirtualFilesByName(FilenameIndex.java:72)
	at com.intellij.psi.search.FilenameIndex.getVirtualFilesByName(FilenameIndex.java:66)
	at lermitage.intellij.extra.icons.enablers.AbstractInFolderEnabler.lambda$init$1(AbstractInFolderEnabler.java:61)
	at dev.failsafe.Functions.lambda$toCtxSupplier$11(Functions.java:243)
	at dev.failsafe.Functions.lambda$get$0(Functions.java:46)
	at dev.failsafe.internal.RetryPolicyExecutor.lambda$apply$0(RetryPolicyExecutor.java:74)
	at dev.failsafe.SyncExecutionImpl.executeSync(SyncExecutionImpl.java:193)
	at dev.failsafe.FailsafeExecutor.call(FailsafeExecutor.java:376)
	at dev.failsafe.FailsafeExecutor.get(FailsafeExecutor.java:112)
	at lermitage.intellij.extra.icons.enablers.AbstractInFolderEnabler.init(AbstractInFolderEnabler.java:58)
	at lermitage.intellij.extra.icons.enablers.AbstractInFolderEnabler.verify(AbstractInFolderEnabler.java:129)
	at lermitage.intellij.extra.icons.ModelCondition.check(ModelCondition.java:115)
	at lermitage.intellij.extra.icons.Model.check(Model.java:300)
	at lermitage.intellij.extra.icons.BaseIconProvider.getIcon(BaseIconProvider.java:222)
	at lermitage.intellij.extra.icons.BaseIconProvider.getIcon(BaseIconProvider.java:143)
	at com.intellij.openapi.vcs.changes.ui.ChangesBrowserNodeRenderer.lambda$setIcon$0(ChangesBrowserNodeRenderer.java:103)
	at com.intellij.openapi.extensions.impl.ExtensionProcessingHelper.computeSafeIfAny(ExtensionProcessingHelper.java:56)
	at com.intellij.openapi.extensions.ExtensionPointName.computeSafeIfAny(ExtensionPointName.java:54)
	at com.intellij.openapi.vcs.changes.ui.ChangesBrowserNodeRenderer.setIcon(ChangesBrowserNodeRenderer.java:103)
	at com.intellij.openapi.vcs.changes.ui.ChangesBrowserChangeNode.setIcon(ChangesBrowserChangeNode.java:83)
	at com.intellij.openapi.vcs.changes.ui.ChangesBrowserChangeNode.render(ChangesBrowserChangeNode.java:70)
	at com.intellij.openapi.vcs.changes.ui.ChangesBrowserNodeRenderer.customizeCellRenderer(ChangesBrowserNodeRenderer.java:54)
	at com.intellij.ui.ColoredTreeCellRenderer.rendererComponentInner(ColoredTreeCellRenderer.java:125)
	at com.intellij.ui.ColoredTreeCellRenderer.getTreeCellRendererComponent(ColoredTreeCellRenderer.java:57)
	at com.intellij.openapi.vcs.changes.ui.ChangesTreeCellRenderer.getTreeCellRendererComponent(ChangesTreeCellRenderer.kt:51)
	at com.intellij.openapi.vcs.changes.ui.HoverChangesTree$MyTreeRenderer.getTreeCellRendererComponent(HoverChangesTree.kt:88)
	at com.intellij.ui.tree.ui.DefaultTreeUI.getRenderer(DefaultTreeUI.java:163)
	at com.intellij.ui.tree.ui.DefaultTreeUI$2.getNodeDimensions(DefaultTreeUI.java:506)
	at java.desktop/javax.swing.tree.AbstractLayoutCache.getNodeDimensions(AbstractLayoutCache.java:497)
	at java.desktop/javax.swing.tree.VariableHeightLayoutCache$TreeStateNode.updatePreferredSize(VariableHeightLayoutCache.java:1344)
	at java.desktop/javax.swing.tree.VariableHeightLayoutCache$TreeStateNode.expand(VariableHeightLayoutCache.java:1465)
	at java.desktop/javax.swing.tree.VariableHeightLayoutCache$TreeStateNode.expand(VariableHeightLayoutCache.java:1272)
	at java.desktop/javax.swing.tree.VariableHeightLayoutCache.ensurePathIsExpanded(VariableHeightLayoutCache.java:967)
	at java.desktop/javax.swing.tree.VariableHeightLayoutCache.setExpandedState(VariableHeightLayoutCache.java:181)
	at com.intellij.ui.tree.ui.DefaultTreeUI$3.setExpandedState(DefaultTreeUI.java:538)
	at java.desktop/javax.swing.plaf.basic.BasicTreeUI.updateExpandedDescendants(BasicTreeUI.java:2003)
	at java.desktop/javax.swing.plaf.basic.BasicTreeUI$Handler.treeExpanded(BasicTreeUI.java:4295)
	at java.desktop/javax.swing.JTree.fireTreeExpanded(JTree.java:2854)
	at java.desktop/javax.swing.JTree.setExpandedState(JTree.java:3767)
	at java.desktop/javax.swing.JTree.expandPath(JTree.java:2297)
	at com.intellij.openapi.vcs.changes.ui.ChangesListView.expandSafe(ChangesListView.java:525)
	at com.intellij.openapi.vcs.changes.ui.ChangesListView.initTreeStateIfNeeded(ChangesListView.java:120)
	at com.intellij.openapi.vcs.changes.ui.ChangesListView.updateModel(ChangesListView.java:103)
	at com.intellij.openapi.vcs.changes.ChangesViewManager$ChangesViewToolWindowPanel.lambda$refreshView$17(ChangesViewManager.java:768)
	at com.intellij.openapi.application.TransactionGuardImpl.runWithWritingAllowed(TransactionGuardImpl.java:209)
	at com.intellij.openapi.application.TransactionGuardImpl.access$100(TransactionGuardImpl.java:21)
	at com.intellij.openapi.application.TransactionGuardImpl$1.run(TransactionGuardImpl.java:191)
	at com.intellij.openapi.application.impl.ApplicationImpl.runIntendedWriteActionOnCurrentThread(ApplicationImpl.java:881)
	at com.intellij.openapi.application.impl.ApplicationImpl$3.run(ApplicationImpl.java:513)
	at com.intellij.openapi.application.impl.FlushQueue.doRun(FlushQueue.java:75)
	at com.intellij.openapi.application.impl.FlushQueue.runNextEvent(FlushQueue.java:118)
	at com.intellij.openapi.application.impl.FlushQueue.flushNow(FlushQueue.java:42)
	at java.desktop/java.awt.event.InvocationEvent.dispatch(InvocationEvent.java:318)
	at java.desktop/java.awt.EventQueue.dispatchEventImpl(EventQueue.java:779)
	at java.desktop/java.awt.EventQueue$4.run(EventQueue.java:730)
	at java.desktop/java.awt.EventQueue$4.run(EventQueue.java:724)
	at java.base/java.security.AccessController.doPrivileged(AccessController.java:399)
	at java.base/java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:86)
	at java.desktop/java.awt.EventQueue.dispatchEvent(EventQueue.java:749)
	at com.intellij.ide.IdeEventQueue.defaultDispatchEvent(IdeEventQueue.java:918)
	at com.intellij.ide.IdeEventQueue._dispatchEvent(IdeEventQueue.java:766)
	at com.intellij.ide.IdeEventQueue.lambda$dispatchEvent$6(IdeEventQueue.java:450)
	at com.intellij.openapi.progress.impl.CoreProgressManager.computePrioritized(CoreProgressManager.java:791)
	at com.intellij.ide.IdeEventQueue.lambda$dispatchEvent$7(IdeEventQueue.java:449)
	at com.intellij.openapi.application.TransactionGuardImpl.performActivity(TransactionGuardImpl.java:105)
	at com.intellij.ide.IdeEventQueue.performActivity(IdeEventQueue.java:624)
	at com.intellij.ide.IdeEventQueue.lambda$dispatchEvent$8(IdeEventQueue.java:447)
	at com.intellij.openapi.application.impl.ApplicationImpl.runIntendedWriteActionOnCurrentThread(ApplicationImpl.java:881)
	at com.intellij.ide.IdeEventQueue.dispatchEvent(IdeEventQueue.java:493)
	at java.desktop/java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:207)
	at java.desktop/java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:128)
	at java.desktop/java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:117)
	at java.desktop/java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:113)
	at java.desktop/java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:105)
	at java.desktop/java.awt.EventDispatchThread.run(EventDispatchThread.java:92)
```

IJ version: IU-222.4167.21
Plugin version: 2022.1.10
MacOS

## Issues

Please describe the issue:

* the **plugin version**
* the **OS and IDE version**. Open your IDE and go to <kbd>Help</kbd>, <kbd>About</kbd>, then <kbd>Copy</kbd>
* the **IDE logs**. Open your IDE and go to <kbd>Help</kbd>, <kbd>Collect Logs and Diagnostic Data</kbd>, then attach files
* the **stacktrace**, if any
* any useful information: what did you do just before the issue, etc.

:warning: This information is needed in order to determine if this is an IDE bug or a plugin bug, and to find a solution or a workaround.

## Feature requests

If you are not comfortable with Java development, you can ask me to support new icons. Please:

* provide SVG (with `height="16" width="16"` in the SVG tag, this is required by IntelliJ 2020.1.4) or 32x32 PNG (with
  transparency) icon(s)
* explain the conditions to apply the icon(s), like filename patterns

You can open an issue, or email me (jonathan.lermitage@gmail.com).

:warning: Feature requests with no icon or no explanations will be ignored.

**Comment by jonathanlermitage** [comment] 2022-09-15 06:08
Will be fixed in next release. This issue was caused by a workaround for IDE filename index issues.

**Closed** 2022-09-16 05:34 UTC
Labels: bug
