### ISSUE TITLE
com.intellij.diagnostic.PluginException: null [Plugin: lermitage.intellij.extra.icons]

### ISSUE THREAD

**Issue by Rami-Suwayyed** [jonathanlermitage/intellij-extra-icons-plugin#130] opened 2023-05-11 11:32 UTC
## Running environment
- Extra Icons plugin version - 2023.2.3
- IDE - PhpStorm 2023.1.1
- OS - Windows 11.0

## Bug description
Please include steps to reproduce (like `go to...`/`click on...` etc.) + expected and actual behaviour.  
Please attach **IDE logs**. Open your IDE and go to <kbd>Help</kbd>, <kbd>Collect Logs and Diagnostic Data</kbd>.

## IDE - additional info
N/A

## IDE - stack trace
```
com.intellij.diagnostic.PluginException: null [Plugin: lermitage.intellij.extra.icons]
	at com.intellij.openapi.options.ConfigurableEP.createProducer(ConfigurableEP.java:311)...
Caused by: com.intellij.openapi.progress.ProcessCanceledException
	at com.intellij.openapi.progress.util.AbstractProgressIndicatorBase.throwIfCanceled(AbstractProgressIndicatorBase.java:158)
	at com.intellij.openapi.progress.util.AbstractProgressIndicatorBase.checkCanceled(AbstractProgressIndicatorBase.java:148)
	at com.intellij.openapi.progress.util.AbstractProgressIndicatorExBase.checkCanceled(AbstractProgressIndicatorExBase.java:103)
	at com.intellij.openapi.progress.util.ProgressWrapper.checkCanceled(ProgressWrapper.java:82)
	at com.intellij.openapi.progress.impl.CoreProgressManager.doCheckCanceled(CoreProgressManager.java:141)
	at com.intellij.openapi.progress.ProgressManager.checkCanceled(ProgressManager.java:227)
	at com.intellij.serviceContainer.ContainerUtilKt.checkCanceledIfNotInClassInit(containerUtil.kt:17)
	at com.intellij.serviceContainer.ComponentManagerImpl.instantiateClass(ComponentManagerImpl.kt:988)
	at com.intellij.serviceContainer.ComponentManagerImpl.instantiateClass(ComponentManagerImpl.kt:1051)
	at com.intellij.openapi.options.ConfigurableEP.instantiateConfigurableProvider(ConfigurableEP.java:319)
	at com.intellij.openapi.options.ConfigurableEP.createProducer(ConfigurableEP.java:297)
	... 32 more

**Comment by jonathanlermitage** [comment] 2023-05-11 13:03
Hi @Rami-Suwayyed  
Did this happen while the IDE was indexing? It seems to be a duplicate of #117 (still opened), but I would need some context info. Thx!

**Comment by jonathanlermitage** [comment] 2023-05-16 22:20
Also, can you please upload IDE logs? It would be very helpful. Thx!

**Comment by jonathanlermitage** [comment] 2023-05-16 22:35
Hi @Rami-Suwayyed  , can you please try this build: 
[Extra Icons-2023.2.3.zip](https://github.com/jonathanlermitage/intellij-extra-icons-plugin/files/11492560/Extra.Icons-2023.2.3.zip)

I reworked the way the IDE filename is use, and it may fix this issue.

**Comment by jonathanlermitage** [comment] 2023-05-17 02:16
I did some changes. This build should be better: 
[Extra Icons-2023.2.3.zip](https://github.com/jonathanlermitage/intellij-extra-icons-plugin/files/11493565/Extra.Icons-2023.2.3.zip)

**Closed** 2023-05-29 06:30 UTC
Labels: bug, waiting for feedback, testing a fix
