### ISSUE TITLE
No Python icon

### ISSUE THREAD

**Issue by ghost** [jonathanlermitage/intellij-extra-icons-plugin#36] opened 2020-05-09 12:32 UTC
need Python icon, please

**Comment by jonathanlermitage** [comment] 2020-05-09 15:59
@weicheng-git Shouldn't you install Python Community plugin instead? Or use PyCharm Community IDE?

**Comment by weicheng-git** [comment] 2020-05-10 01:01
I use Ultimate IntelliJ IDEA, can't find Python icon

**Comment by jonathanlermitage** [comment] 2020-05-10 01:07
Tried IJ Ultimate + Python plugin: it shows Python icon.

![py-icon](https://user-images.githubusercontent.com/857535/81488611-509f6200-926b-11ea-99e6-754222b2bd46.png)

**Comment by jonathanlermitage** [comment] 2020-05-10 01:08
If you opened a non-Python project, you may have to open a python file first, then IDE will ask you how to open it (as a text file, etc.). After that, Python icon will be used.

**Comment by weicheng-git** [comment] 2020-05-10 01:10
thanks.

**Comment by jonathanlermitage** [comment] 2020-05-10 01:12
you're welcome :)

**Comment by mallowigi** [comment] 2020-09-05 19:25
Reopening this because it doesn't work for me. I still get the default python icon. I'm on PyCharm Pro 2020.2.

**Comment by jonathanlermitage** [comment] 2020-09-05 19:33
@mallowigi do you see this icon? ![py-icon](https://user-images.githubusercontent.com/857535/81488611-509f6200-926b-11ea-99e6-754222b2bd46.png)

This is expected behavior, Extra Icons plugin doesn't provide icon for Python files.

**Comment by mallowigi** [comment] 2020-09-05 19:38
Yes, but I added my own icon with regex .`*\.py`

It works only for tabs, not editorView.

**Comment by jonathanlermitage** [comment] 2020-09-05 19:50
This is a new bug. Can you open a dedicated issue please?
Thx!

**Comment by mallowigi** [comment] 2020-09-05 19:56
To be honest it's a JetBrains SDK issue. Apparently in the PyCharm SDK when they implemented the Python PSI nodes, they made it so that the PythonPsiFile provides their own icons, and so IconProvider doesn't run for such nodes. It's the same thing with Java Classes/Interfaces/Enums/etc icons.

That means that non-Pycharm IDEs will see the icon just like they defined. But PyCharm or IDEs with the Python plugin will see the default icon (and Mako, AppEngine, Chameleon... as well).

I have the same issue in my plugin (Atom File Icons) and I was wondering whether you had the same problem.

**Comment by jonathanlermitage** [comment] 2020-09-05 20:05
Thx for these details. I think we can open a issue on JetBrains Youtrack.

Also, I can add Python icon to Extra Icons plugin. Something like this? https://seeklogo.com/vector-logo/273830/python

**Comment by jonaswouters** [comment] 2023-07-18 16:22
was there ever a ticket created? The issue still persists.

**Comment by jonathanlermitage** [comment] 2023-07-18 20:59
Thx for this link! Just up-voted (sorry, I have so many projects, and a big lack of free-time this year, I forgot to check if the youtrack issue was created 😅).  
If many users upvote, I hope JetBrains may give it more attention 🤞

**Comment by jonathanlermitage** [comment] 2023-07-18 21:02
I will add this link in Extra Icons plugin's description. I did this for https://youtrack.jetbrains.com/issue/IDEA-321006 and, I won't say this is linked, but it received some upvotes, and a JetBrains employee has been assigned to it just after that ^^.

**Comment by jonaswouters** [comment] 2023-07-19 07:17
This is also the case for Goland with the Go test files *_test.go. 

This was discussed a long time ago in @mallowigi 's project here: https://github.com/mallowigi/a-file-icon-idea/issues/258

**Comment by jonaswouters** [comment] 2023-07-19 12:29
It doesn't work there either. Same problem, different IDE.

**Comment by jonathanlermitage** [comment] 2023-10-19 11:24
Just for info: similar problem with .tree and .list files in Wriserside IDE (no problem with Writerside plugin running inIntelliJ).

**Comment by jonathanlermitage** [comment] 2023-11-05 02:05
Just a reminder: upvoting https://youtrack.jetbrains.com/issue/PY-44417/IconProvider-doesnt-replace-Python-Icons would help, as the problem is on jetbrains side.

**Comment by jonathanlermitage** [comment] 2023-11-05 15:59
Should be fixed. Tested in WriterSide IDE.

**Closed** 2023-11-05 15:58 UTC
Labels: see youtrack.jetbrains.com
