### ISSUE TITLE
`com.intellij.diagnostic.PluginException: null` caused by `com.intellij.openapi.progress.ProcessCanceledException`

### ISSUE THREAD

**Issue by PawelLipski** [jonathanlermitage/intellij-extra-icons-plugin#117] opened 2023-02-20 16:41 UTC
**Plugin version:** 2023.1.1

**IDE version:**

```
Build #IU-222.4459.24, built on November 22, 2022

Runtime version: 17.0.5+7-b469.71 x86_64
VM: OpenJDK 64-Bit Server VM by JetBrains s.r.o.
```

**Stack trace:**

```
com.intellij.diagnostic.PluginException: null [Plugin: lermitage.intellij.extra.icons]
	at com.intellij.openapi.options.ConfigurableEP.createProducer(ConfigurableEP.java:311)
	at com.intellij.openapi.util.NotNullLazyValue$2.compute(NotNullLazyValue.java:71)
	at com.intellij.openapi.util.AtomicNotNullLazyValue.getValue(AtomicNotNullLazyValue.java:28)
	at com.intellij.openapi.options.ConfigurableEP.canCreateConfigurable(ConfigurableEP.java:377)
	at com.intellij.openapi.options.ex.ConfigurableWrapper.wrapConfigurable(ConfigurableWrapper.java:29)
	at com.intellij.openapi.options.ex.ConfigurableExtensionPointUtil.getConfigurables(ConfigurableExtensionPointUtil.java:382)
	at com.intellij.ide.actions.ShowSettingsUtilImpl.getConfigurables(ShowSettingsUtilImpl.java:65)
	at com.intellij.ide.util.gotoByName.GotoActionModel.lambda$new$0(GotoActionModel.java:80)
	at com.intellij.openapi.util.NotNullLazyValue$4.compute(NotNullLazyValue.java:120)
	at com.intellij.openapi.util.NotNullLazyValue$4.getValue(NotNullLazyValue.java:105)
	at com.intellij.ide.util.gotoByName.GotoActionModel.getConfigurablesNames(GotoActionModel.java:358)
	at com.intellij.ide.util.gotoByName.GotoActionItemProvider.processOptions(GotoActionItemProvider.java:151)
	at com.intellij.ide.util.gotoByName.GotoActionItemProvider.filterElements(GotoActionItemProvider.java:97)
	at com.intellij.ide.actions.searcheverywhere.ActionSearchEverywhereContributor.lambda$fetchWeightedElements$1(ActionSearchEverywhereContributor.java:99)
	at com.intellij.openapi.progress.impl.CoreProgressManager.lambda$executeProcessUnderProgress$12(CoreProgressManager.java:608)
	at com.intellij.openapi.progress.impl.CoreProgressManager.registerIndicatorAndRun(CoreProgressManager.java:683)
	at com.intellij.openapi.progress.impl.CoreProgressManager.computeUnderProgress(CoreProgressManager.java:639)
	at com.intellij.openapi.progress.impl.CoreProgressManager.executeProcessUnderProgress(CoreProgressManager.java:607)
	at com.intellij.openapi.progress.impl.ProgressManagerImpl.executeProcessUnderProgress(ProgressManagerImpl.java:60)
	at com.intellij.ide.actions.searcheverywhere.ActionSearchEverywhereContributor.fetchWeightedElements(ActionSearchEverywhereContributor.java:98)
	at com.intellij.ide.actions.searcheverywhere.MixedResultsSearcher$ContributorSearchTask.run(MixedResultsSearcher.java:178)
	at com.intellij.util.ConcurrencyUtil.runUnderThreadName(ConcurrencyUtil.java:212)
	at com.intellij.util.ConcurrencyUtil.lambda$underThreadNameRunnable$3(ConcurrencyUtil.java:200)
	at com.intellij.openapi.application.impl.ApplicationImpl$1.run(ApplicationImpl.java:297)
	at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:539)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
	at java.base/java.util.concurrent.Executors$PrivilegedThreadFactory$1$1.run(Executors.java:702)
	at java.base/java.util.concurrent.Executors$PrivilegedThreadFactory$1$1.run(Executors.java:699)
	at java.base/java.security.AccessController.doPrivileged(AccessController.java:399)
	at java.base/java.util.concurrent.Executors$PrivilegedThreadFactory$1.run(Executors.java:699)
	at java.base/java.lang.Thread.run(Thread.java:833)
Caused by: com.intellij.openapi.progress.ProcessCanceledException
	at com.intellij.openapi.progress.util.AbstractProgressIndicatorBase.throwIfCanceled(AbstractProgressIndicatorBase.java:157)
	at com.intellij.openapi.progress.util.AbstractProgressIndicatorBase.checkCanceled(AbstractProgressIndicatorBase.java:147)
	at com.intellij.openapi.progress.util.AbstractProgressIndicatorExBase.checkCanceled(AbstractProgressIndicatorExBase.java:103)
	at com.intellij.openapi.progress.util.ProgressWrapper.checkCanceled(ProgressWrapper.java:82)
	at com.intellij.openapi.progress.impl.CoreProgressManager.doCheckCanceled(CoreProgressManager.java:143)
	at com.intellij.openapi.progress.ProgressManager.checkCanceled(ProgressManager.java:219)
	at com.intellij.serviceContainer.ContainerUtilKt.checkCanceledIfNotInClassInit(containerUtil.kt:16)
	at com.intellij.serviceContainer.ComponentManagerImpl.instantiateClass(ComponentManagerImpl.kt:839)
	at com.intellij.serviceContainer.ComponentManagerImpl.instantiateClass(ComponentManagerImpl.kt:900)
	at com.intellij.openapi.options.ConfigurableEP.instantiateConfigurableProvider(ConfigurableEP.java:319)
	at com.intellij.openapi.options.ConfigurableEP.createProducer(ConfigurableEP.java:297)
	... 32 more
```

**Comment by jonathanlermitage** [comment] 2023-02-20 19:14
@PawelLipski  I think this is a duplicate of #108  #42. It may be an IntelliJ bug. Extra icons registers a task which queries the IDE filename index when the IDE is in _smart mode_ (when all indexing tasks completed), and I'm wondering if there is a bug in IntelliJ.  

Do you see this error regularly?  
Could you please go to Help > Collect Logs and Diagnostic Data, and post files? Thanks!  

I will see if I find similar issues on Youtrack...

**Comment by PawelLipski** [comment] 2023-02-21 10:34
> Could you please go to Help > Collect Logs and Diagnostic Data, and post files? Thanks!

Whoops sorry I can't share my IDEA logs as it's got proprietary plugins from my client running ☹️ 

> Do you see this error regularly?

First time ever I've seen that :/ but yeah indeed, seems a duplicate of #42 and #108 🤔

**Comment by jonathanlermitage** [comment] 2023-02-21 15:28
No problem 😁  
I will raise an issue in Youtrack, because the error `PluginException: null` generated by the IDE simply doesn't help. They need to provide more information.

**Comment by jonathanlermitage** [comment] 2023-05-16 22:37
Hi @PawelLipski, can you please try this build: 
[Extra Icons-2023.2.3.zip](https://github.com/jonathanlermitage/intellij-extra-icons-plugin/files/11492560/Extra.Icons-2023.2.3.zip)

I reworked the way the IDE filename is used, and the issues looks a bit similar to #130. This build may fix this issue.

**Comment by jonathanlermitage** [comment] 2023-05-17 02:16
I did some changes. This build should be better: 
[Extra Icons-2023.2.3.zip](https://github.com/jonathanlermitage/intellij-extra-icons-plugin/files/11493565/Extra.Icons-2023.2.3.zip)

**Comment by jonathanlermitage** [comment] 2023-05-18 01:50
No problem. Other people faced similar issue and, if this is fixed, I will create a special release for older IDEs.

**Comment by jonathanlermitage** [comment] 2023-05-21 21:43
Hi @PawelLipski , I just prepared a release for 2022 IDEs. It should be available on the marketplace next week. You can also install it from here: 
[Extra Icons-2023.2.4-221.zip](https://github.com/jonathanlermitage/intellij-extra-icons-plugin/files/11525631/Extra.Icons-2023.2.4-221.zip)

**Comment by PawelLipski** [comment] 2023-05-22 07:53
Okay! thanks a lot :)

**Comment by jonathanlermitage** [comment] 2023-06-12 03:10
Plugin release 2023.2.6 published to the marketplace. It contains more fixes. It should be available in ~2 days.

**Closed** 2023-06-12 03:10 UTC
Labels: bug, waiting for feedback, testing a fix
