### ISSUE TITLE
Abstract Class Icon Replacement Issue

### ISSUE THREAD

**Issue by fronskyofficial** [jonathanlermitage/intellij-extra-icons-plugin#148] opened 2023-07-26 13:04 UTC
# Issue Description

When the New UI is enabled, the plugin fails to replace the abstract class icon, resulting in a mismatch with the styling of other icons.

Example when using New UI:
[https://prnt.sc/I-1tMMHPydzU](https://prnt.sc/I-1tMMHPydzU)

Example when using Old UI:
[https://prnt.sc/_VH_InDyrcH9](https://prnt.sc/_VH_InDyrcH9)

# Issue Details

- **Plugin Version:** 2023.2.8-231 <br />
- **OS and IDE Version:** <br />
    - **OS:** Windows 11 Pro 22H2 *(OS Build 23506.1000)* <br />
    - **IDE:** IntelliJ IDEA 2023.2

**Comment by jonathanlermitage** [comment] 2023-07-26 14:06
Yeah, this issue is caused by https://youtrack.jetbrains.com/issue/IDEA-321006  
I am waiting for a fix at the IDE level.

**Comment by jonathanlermitage** [comment] 2023-10-12 22:18
It should work in IJ 2023**.3** as [IDEA-321006](https://youtrack.jetbrains.com/issue/IDEA-321006) has been fixed in 2023.3 EAP 🥳

**Closed by jonathanlermitage** 2023-10-12 22:18 UTC
Labels: bug, see youtrack.jetbrains.com
